version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g serverless
      - sls plugin install -n serverless-python-requirements
      - pip install poetry
  build:
    commands:
      - sls deploy