service: aws-slack-notifier

provider:
  name: aws
  region: ap-northeast-1
  stage: ${env:STAGE}
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  notify_bill:
    handler: functions/notify_bill.main

plugins:
  - serverless-python-requirements
