service: aws-slack-notifier

provider:
  name: aws
  region: ap-northeast-1
  stage: ${env:STAGE}
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  notify_bill_daily:
    handler: functions/notify_bill.daily
    environment:
      SECRETS_MANAGER_ID: !Ref SecretsManager
  notify_bill_monthly:
    handler: functions/notify_bill.monthly
    environment:
      SECRETS_MANAGER_ID: !Ref SecretsManager
    events:
      schedule:
        - cron(0 9 * * *)

resources:
  Resources:
    SecretsManager: ${file(./cfn/resources/Secret.yml)}

plugins:
  - serverless-python-requirements
