service: aws-slack-notifier

provider:
  name: aws
  region: ap-northeast-1
  stage: ${env:STAGE}
  runtime: python3.9
  lambdaHashingVersion: 20201221

functions:
  notify_bill:
    handler: functions/notify_bill.main
    environment:
      SECRETS_MANAGER_ID: !Ref SecretsManager

resources:
  Resources:
    SecretsManager: ${file(./cfn/resources/Secret.yml)}

plugins:
  - serverless-python-requirements
