service: aws-slack-notifier

provider:
  name: aws
  region: ap-northeast-1
  stage: ${env:STAGE}
  runtime: python3.9
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogStream
        - logs:PutLogEvents
        - logs:CreateLogGroup
      Resource:
        - "*"
    - Effect: Allow
      Action: "ce:GetCostAndUsage"
      Resource: "*"
    - Effect: Allow
      Action: "secretsmanager:GetSecretValue"
      Resource: !Ref SecretsManager

functions:
  notify_bill_daily:
    handler: functions/notify_bill.daily
    environment:
      SECRETS_MANAGER_ID: !Ref SecretsManager
    events:
      - schedule: cron(0 9 * * ? *)

resources:
  Resources:
    SecretsManager: ${file(./cfn/resources/Secret.yml)}

plugins:
  - serverless-python-requirements
